defaults:
  - _self_           # This is the config file for the exchange model
  - common           # This is the common config file for all the exchange models

name: 'Bitmex'       # Name of the exchange (should not be changed!)
binsize: 1d          # Timeframe of the data (1d, 1h, 1m, 1s)
batch_size: 750      # Number of rows to be fetched at once
symbol: "XBTUSD"     # Symbol of the coin (XBTUSD, ETHUSD, ...)



#Bitcoin: XBTUSD
#Ethereum: ETHUSD
#BNB: BNBUSD
#Cardano: ADAUSD
#Dogecoin: DOGEUSD
#Solana: SOLUSD
#Polkadot: DOTUSD
#Litecoin: LTCUSD
#TRON: TRXUSD
#Avalanche: AVAXUSD
#Chainlink: LINKUSD
#Aptos: APTUSD
#Bitcoin Cash: BCHUSD
#NEAR Protocol: NEARUSD
#ApeCoin: APEUSD
#Cronos: CROUSD
#Axie Infinity: AXSUSD
#EOS: EOSUSD

